In [1]:
import numpy as np

In [2]:
Q = np.array([[0, 0],
              [0, 0],
              [0, 0],
              [0, 0]])

In [3]:
R = np.array([[0, 0],
              [1, 1],
              [0, 0],
              [2, 2]])

In [4]:
Tb = np.array([[0, 0.9, 0.1, 0],
               [0.9, 0.1, 0, 0],
               [0, 0, 0.1, 0.9],
               [0.9, 0, 0, 0.1]])

In [5]:
Tc = np.array([[0, 0.1, 0.9, 0],
               [0.9, 0.1, 0, 0],
               [0, 0, 0.1, 0.9],
               [0.9, 0, 0, 0.1]])

In [8]:
Q = R + 0.9 * np.hstack([Tb@np.max(Q, axis=1, keepdims=True), Tc@np.max(Q, axis=1, keepdims=True)])

In [9]:
Q

array([[0., 0.],
       [1., 1.],
       [0., 0.],
       [2., 2.]])

In [10]:

Q = R + 0.9 * np.hstack([Tb@np.max(Q, axis=1, keepdims=True), Tc@np.max(Q, axis=1, keepdims=True)])

In [11]:
Q

array([[0.81, 0.09],
       [1.09, 1.09],
       [1.62, 1.62],
       [2.18, 2.18]])

In [12]:
Q = R + 0.9 * np.hstack([Tb@np.max(Q, axis=1, keepdims=True), Tc@np.max(Q, axis=1, keepdims=True)])

In [13]:
Q

array([[1.0287, 1.4103],
       [1.7542, 1.7542],
       [1.9116, 1.9116],
       [2.8523, 2.8523]])