# Multiclass Classification

In [4]:
import numpy as np

def softmax(v):
    return np.exp(v) / sum(np.exp(v))

In [6]:
W = np.array([[1, -1, -2],
              [-1, 2, 1]])
a = softmax(W.T@np.array([1, 1]).T)

In [7]:
a - np.array([0, 1, 0])

array([ 0.24472847, -0.33475904,  0.09003057])

In [8]:
a

array([0.24472847, 0.66524096, 0.09003057])

In [9]:
grad_w = np.array([[ 0.24472847, -0.33475904,  0.09003057], [ 0.24472847, -0.33475904,  0.09003057]])

In [11]:
W = W.astype('float64') - 0.5 * grad_w

In [12]:
W

array([[ 0.87763576, -0.83262048, -2.04501528],
       [-1.12236424,  2.16737952,  0.95498472]])

In [13]:
softmax(W.T@np.array([1, 1]).T)

array([0.15918761, 0.77245284, 0.06835955])

# Neural Networks

In [14]:
import torch as T

In [17]:
W = np.array([[1, 0, -1, 0],
              [0, 1, 0, -1],
              [-1, -1, -1, -1]])

In [18]:
V = np.array([[1, -1],
              [1, -1],
              [1, -1],
              [1, -1],
              [0,  2]])

In [39]:
def relu(x):
    return np.maximum(0, x)

In [48]:
x = np.array([3, 14, 1]).reshape(-1, 1)
x = relu(W.T@x)
x = np.vstack([x, np.ones(1).reshape(1, 1)])
print(x)

[[ 2.]
 [13.]
 [ 0.]
 [ 0.]
 [ 1.]]


In [49]:
softmax(V.T@x)

array([[1.00000000e+00],
       [6.91440011e-13]])

In [53]:
x = np.array([[0.5, 0.5],
              [0.0, 2.0],
              [-3,  0.5]]).T

In [55]:
x = np.vstack([x, np.ones((1, 3))])

In [57]:
relu(W.T@x)

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 2.],
       [0., 0., 0.]])

In [59]:
softmax([0, 2])

array([0.11920292, 0.88079708])